apiVersion: v1
kind: Service
metadata:
    name: "kicasaks-e501"
    labels:
        app: "kicasaks-e501"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kicasaks-e501"